version: '3.9'

services:
  # nestjs:
  #   container_name: api
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - ${PORT}:${PORT}
  #   volumes:
  #     - '.:/usr/src/app/'
  #     - "/usr/src/app/node_modules"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - api-networks
  mongo:
    container_name: db
    image: bitnami/mongodb:latest 
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${PASSWORD_DB}
      - MONGODB_REPLICA_SET_KEY=replica123
      - MONGODB_USERNAME=${USERNAME_DB}
      - MONGODB_PASSWORD=${PASSWORD_DB}
      - MONGODB_DATABASE=${DB_NAME}
    ports:
      - ${PORT_DB}:${PORT_DB}
    networks:
      - api-networks
    volumes:
      - "mongo-data:/bitnami/mongodb"
    expose:
      - ${PORT_DB}

networks:
  api-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: "local"
